### ISSUE TITLE
Getting search option to work properly

### ISSUE THREAD

**Issue by psykobilliethekid** [EtienneWan/tmdb-js#1]
Can you give an example of how line 7 in the tmdb.js file should look if using the /search/movie method? I'm having some trouble getting it to pull data from the site. 

As an example, I have this for line 7 in my code: call: function(/search/movie, ?=title, success, error)
an I keep getting an error saying it has an unexpected string.

**Comment by EtienneWan** [comment]
The url parameters you give when you `tmdb.call` must be in JSON format.
So for example, when you're looking for the Star Wars films : 
```js
tmdb.call('/search/movie',
  {
    "query": "Star Wars",
    "include_adult": false
  },
  success,
  function(e){
    console.error("An error happened : "+e);
  }
);
```

**Comment by psykobilliethekid** [comment]
I'm still getting the same error at tmdb.call('/search/movie',
Is this from me working on localhost?

And I wanted to ask, how would you set up the query so it takes the value from a submitted search? Would it be something like this:
```
{ 
"query":$(#search).val(),
"include_adult": false
}
```

I apologize if my answers are trivial - this is my first API site so I'm having a little bit of trouble.

**Comment by EtienneWan** [comment]
Did you set your API key line 3 in tmdb.js ? If not, you will only get HTTP 401 Errors (Unauthorized).
You can request an API key on https://www.themoviedb.org by crating an account, or you can browse http://docs.themoviedb.apiary.io/ to try the API without an API key (by changing the uri in tmdb.js with the uri for a Mock Server)

For your second question, yes, it will be this way to get the value of a text input.
If you have any questions left, I'm still here ;)

**Comment by psykobilliethekid** [comment]
Thanks for being so patient with me. Yes, I have an API key set on line 3. I'm also running the site off of http-server that I started in the Command Console. When I run the site, it asks me if I;m serving from the file system and if I want to add files to my workspace. Maybe this is why I keep getting the error. Any ideas?

I'll see if I can pull information from the Mock Server. I do have an API key so, is this how I would set up  lines 1-17 without the api key?

```
(function() { 
	window.tmdb = {
		"api_key": " ",
		"base_uri": "http://private-anon-b8582645b-themoviedb.apiary-mock.com/3/search/movie",
		"images_uri": "http://image.tmdb.org/t/p",
		"timeout": 5000,
		tmdb.call('/search/movie', 
			{
				"query": $(#search).val(),
				"include_adult": false
			}, 
			success, 
			function(e){
				console.error("An error happened: " +e);
				}
			);
		{
```

**Comment by EtienneWan** [comment]
Are you modifying the content of tmdb.js (except the api_key and URIs ? You don't have to, it will break everything. ;)

Let's start from zero.
Download again tmdb.js to be sure that you got an unmodified file.
Check that you have this included in your HTML file (accord the path for the file):
```html
<script src="tmdb.js"></script>
``` 
And then you can use tmdb.call inside your HTML file, like this : 
```html
<script>
tmdb.call('/search/movie', 
  {
    "query": $(#search).val(),
    "include_adult": false
  }, 
  success, 
  function(e){
    console.error("An error happened: "+e);
  }
);

function success(e){
  alert("I got results, check console.");
  console.log(e);
</script>
```

**Comment by psykobilliethekid** [comment]
To answer your first question, yes I was editing the tmbd.js file, so that explains the first set of errors I was getting. I went back and followed what you suggested from step 1 and added the script to my html.  I'm still getting an error and have no idea why. Here's a screenshot of what I'm getting - hopefully this will help with the confusion. 

![image](https://cloud.githubusercontent.com/assets/4343088/8967211/94d77bde-3603-11e5-9a26-cea31f798962.png)

**Comment by EtienneWan** [comment]
This is a syntax error, line 111 (?), but I can't see from here. I need to see the code :)

**Comment by psykobilliethekid** [comment]
Yeah hang on let me move the screen up and zoom in...
Hopefully this will help. Sorry about that - didn't know how well the image would show the error.
![image](https://cloud.githubusercontent.com/assets/4343088/8967844/8b1ce24c-3607-11e5-9625-abfb811b29c8.png)

**Comment by EtienneWan** [comment]
I don't use jQuery, but I think it must be $("#search") instead of $(#search)

**Comment by EtienneWan** [comment]
Than you'll have to attach this code (tmdb.call part) to the submit button.

**Comment by psykobilliethekid** [comment]
Ok! It was the jQuery part, and some syntax errors, but I was able to get everything set up properly with no errors. Sadly I'm still getting the "Serving from file system" alert. Really not sure what that's about. Any ideas? Here's a screenshot of what I'm talking about.

![image](https://cloud.githubusercontent.com/assets/4343088/8969127/74f03e6c-360f-11e5-92dd-cdfa001e62f0.png)

**Comment by EtienneWan** [comment]
Ah ok, I got it now. It's a Chrome feature, a built-in code editor for web languages.
It's not a problem. I thought you were saying at start that you were on file:// and not with an http server (which can cause AJAX problem sometimes) ;)

**Comment by psykobilliethekid** [comment]
No I'm on http-server. glad to know it isn't something I'm doing wrong. I'll try things out on file:// and hope for the best. Thanks for all your help! :)

**Comment by EtienneWan** [comment]
What I said was confused
On file:// there can be Ajax problem, not when you're using an Http server.
So stay with localhost and your server.
Good luck with your project ;-)
