### ISSUE TITLE
Link to API Documentation in Readme is broken

### ISSUE THREAD

**Issue by kaptainkommie** [EtienneWan/tmdb-js#2]
The link to the API Documentation referenced in your README is "deprecated".  

The current link is : [https://developers.themoviedb.org/3/getting-started](https://developers.themoviedb.org/3/getting-started)

Does this mean that your code is not compatible with Version 3 of the API?

**Comment by EtienneWan** [comment]
Only the location indicated in the README is deprecated, the actual version of the API is v3 and this is the version used inside tmdb.js (see https://github.com/EtienneWan/tmdb-js/blob/master/tmdb.js#L4)
In conclusion, this should still work (I wrote it 2 years ago as a helper, it's not well designed but works) if there has been no major change to the API (in a normal case, if there has been one, the API would now be v4). Don't hesitate to open an issue if it doesn't work properly.
